{{- range .Values.nodepools }}
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: {{ .name }}
spec:
  weight: {{ .weight | default 10 }}
  template:
    {{- if .labels }}
    metadata:
      labels:
        {{- range $k, $v := .labels }}
        {{ $k }}: {{ $v }}
        {{- end }}
    {{- end }}
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: {{ .nodeClassName }}
      {{- if .taints }}
      taints:
        {{- range .taints }}
        - key: {{ .key }}
          value: {{ .value }}
          effect: {{ .effect }}
        {{- end }}
      {{- end }}
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: {{ .capacityTypes | toJson }}
        - key: kubernetes.io/arch
          operator: In
          values: {{ .arch | default (list "amd64") | toJson }}
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: {{ .instanceCategories | toJson }}
        - key: karpenter.k8s.aws/instance-generation
          operator: {{ .instanceGeneration.operator | default "Gt" }}
          values: {{ .instanceGeneration.values | toJson }}
        - key: karpenter.k8s.aws/instance-size
          operator: NotIn
          values: {{ .instanceSizeExcludes | default (list "nano" "micro" "small") | toJson }}
        {{- if .capacitySpreadLabels }}
        - key: capacity-spread
          operator: In
          values: {{ .capacitySpreadLabels | toJson }}
        {{- end }}
        {{- range $k, $v := .labels }}
        - key: {{ $k }}
          operator: In
          values: [{{ $v | quote }}]
        {{- end }}
  disruption:
    consolidationPolicy: {{ .consolidationPolicy }}
    consolidateAfter: {{ .consolidateAfter }}
  {{- if .limits }}
  limits:
    cpu: {{ .limits.cpu | quote }}
    memory: {{ .limits.memory }}
  {{- end }}
{{- end }}
