{{- range .Values.nodeclasses }}
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: {{ .name }}
spec:
  role: {{ include "karpenter-nodes.nodeRole" $ }}
  kubelet:
    maxPods: {{ .maxPods | default 110 }}
  amiSelectorTerms:
    - alias: {{ .amiAlias | default "al2023@latest" }}
  subnetSelectorTerms:
    - tags:
        Tier: {{ .subnetTier | default "private" }}
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ include "karpenter-nodes.discoveryTag" $ }}
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: {{ .volumeSize | default "50Gi" }}
        volumeType: {{ .volumeType | default "gp3" }}
        encrypted: true
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  tags:
    karpenter.sh/discovery: {{ include "karpenter-nodes.discoveryTag" $ }}
    workload: {{ .name }}
{{- end }}
