{{- if .Values.argocd }}
apiVersion: v1
strigData:
  name: {{ .Values.argocd.repo.name }}
  type: {{ .Values.argocd.repo.type }}
  url: {{ .Values.argocd.repo.url }}
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: {{ .Release.Name }}-repository
  namespace: {{ .Release.Namespace }}
type: Opaque
{{- end }}
