apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      {{- with .Values.annotations }}
      annotations: 
        {{- range $k, $v := . }}
        {{ $k }}: {{ $v | quote }}
        {{- end }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      {{- if .Values.serviceAccount }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      containers:
      - name: s3-proxy
        image: {{ .Values.image | default "s3-proxy:2.0" }}
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu  }}
        {{- with .Values.envs }}
        envs:
          {{- toYaml . | nindent 10 }}
        {{- end}}

